version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8080:8080"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"